sudo: false
language: node_js
node_js:
  - "node"
  - "6"
cache:
  directories:
    - $HOME/.yarn-cache
before_install:
  - npm install -g yarn
install:
  - yarn
# The script actions are to check the project is valid.
# If using Travis for the project PLEASE MODIFY/REMOVE AS NEEDED.
script:
  - yarn run lint
  - yarn run coverage
